// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "b9279c87-722a-4677-b4d9-285675a5f2b9");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.previous.reasons", "[\"app.update.background.enabled=false\",\"not default profile\"]");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1634266946);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1634266918);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1634266918);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1634266916);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 117);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ccb3c473-a693-4810-9e60-b95312559ae0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1634266917);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1634266918411");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1634288518411");
user_pref("browser.search.region", "CA");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.homepage_override.buildID", "20210927210923");
user_pref("browser.startup.homepage_override.mstone", "93.0");
user_pref("browser.startup.lastColdStartupCheck", 1634266917);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1634266917962");
user_pref("distribution.iniFile.exists.appversion", "93.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CA");
user_pref("dom.push.userAgentID", "98efb9d9bacf4b30a23ef29f3681ce13");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210927210923");
user_pref("extensions.lastAppVersion", "93.0");
user_pref("extensions.lastPlatformVersion", "93.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"acbeb785-47d3-45ca-9ebf-c5b741cd239e\",\"formautofill@mozilla.org\":\"e4ca1f77-ad1c-4e14-a02c-7fcc15d4f84c\",\"pictureinpicture@mozilla.org\":\"b1a2f4e3-2d8e-43fa-9a41-d71adaf4603b\",\"screenshots@mozilla.org\":\"e8abfddc-b183-4e5f-8a58-a5f7b3409d21\",\"webcompat-reporter@mozilla.org\":\"98bda104-63cd-4d43-bbd5-4a8a6c3327e9\",\"webcompat@mozilla.org\":\"0cdd812a-41bc-4d65-8403-a775f232c132\",\"default-theme@mozilla.org\":\"6a671a5a-1fc6-4442-a484-32896f2786de\",\"google@search.mozilla.org\":\"3a642751-9411-449b-8083-e8aeaebc45c9\",\"wikipedia@search.mozilla.org\":\"a07cccb7-6aef-43a6-94df-509408c25567\",\"bing@search.mozilla.org\":\"7db09891-40d2-4f2e-869c-91ded249ce31\",\"ddg@search.mozilla.org\":\"7adfa85c-5686-473f-ba6c-7ee66dc849c8\",\"ebay@search.mozilla.org\":\"ef95e6c3-9879-4ced-b066-3185dcf1dda0\",\"amazon@search.mozilla.org\":\"4621c84c-11d2-4b24-8a70-1a219419e922\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1634266917);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx-shader-check.build-version", "20210927210923");
user_pref("gfx-shader-check.device-id", "0x1f08");
user_pref("gfx-shader-check.driver-version", "30.0.14.7155");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "93.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x1f08");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "30.0.14.7155");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":null,\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x1f08");
user_pref("sanity-test.driver-version", "30.0.14.7155");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210927210923");
user_pref("security.sandbox.content.tempDirSuffix", "{bac1dc9c-824c-41ec-9665-08e9406a89f0}");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1634266915);
user_pref("toolkit.telemetry.cachedClientID", "9f2b60e1-a90c-4b1f-83f2-1de42cc3e716");
user_pref("toolkit.telemetry.previousBuildID", "20210927210923");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
